import { TRPCError } from '@trpc/server';
import { and, asc, desc, eq, isNotNull, isNull, ne, or, sql } from 'drizzle-orm';
import { alias } from 'drizzle-orm/pg-core';
import { z } from 'zod';

import { conversationMembers, conversations, deviceKeyPackages, devices, messages, users } from '../../db/schema.js';
import { notifyNewMessage } from '../../lib/pushDelivery.js';
import type { Context } from '../context.js';
import { enforceRateLimit, protectedProcedure, router } from '../trpc.js';

/**
 * Phase 5D hardening: rejects the call if the *caller's own* device
 * (`ctx.device.id`, trusted from the access token — see context.ts) has
 * since been revoked. `context.ts` deliberately doesn't hit the database
 * on every request (a per-request DB check there would turn the
 * intentionally stateless, JWT-expiry-based auth model into a
 * semi-stateful one for every single endpoint, which is a bigger change
 * than this phase's "harden, don't rebuild" scope) — that leaves up to a
 * ~15-minute window (the access token TTL) where a just-revoked device's
 * token still verifies. For the specific E2EE endpoints where a revoked
 * device actively publishing new trust material or messages during that
 * window would matter most (as opposed to e.g. read-only polling), this
 * closes that window with one targeted DB check rather than changing the
 * shared auth middleware everyone else also goes through.
 */
async function assertCallerDeviceActive(ctx: Pick<Context, 'db'> & { device: { id: string } }): Promise<void> {
  const [device] = await ctx.db.select({ revokedAt: devices.revokedAt }).from(devices).where(eq(devices.id, ctx.device.id)).limit(1);
  if (!device || device.revokedAt) {
    throw new TRPCError({ code: 'UNAUTHORIZED', message: 'This device has been signed out.' });
  }
}

/**
 * Ciphertext transport for the Phase 5C E2EE proof. No transformer is
 * configured for this tRPC router (plain JSON over the wire, per the
 * existing Phase 4 setup), so binary payloads — KeyPackages, Welcome
 * messages, application ciphertext — travel as base64 strings and are
 * decoded to `Buffer` immediately at the boundary, before anything
 * touches the database. Every column these write to is `bytea`; nothing
 * here ever inspects, transforms, or logs the decoded bytes' content —
 * see the Phase 5C report's "what the server can/can't see" section.
 */
const base64Bytes = z.string().refine(
  (value) => {
    try {
      return Buffer.from(value, 'base64').length > 0;
    } catch {
      return false;
    }
  },
  { message: 'Expected non-empty base64-encoded bytes' },
);

export const e2eeRouter = router({
  /**
   * Phase 6: writes the account-level MLS identity signing public key
   * (`users.identitySigningPublicKey`) — a column that has existed since
   * Phase 5A/5B but that no endpoint ever wrote to until now. This key
   * is meant to exist exactly once per account, generated by whichever
   * device runs E2EE setup first; set-once/idempotent rather than
   * overwritable, matching the approved design ("never regenerated or
   * restored by recovery" — see auth.ts's recovery flow doc comment).
   * If the account already has one on file, this call is a no-op
   * returning success rather than an error, so a device's own retry or
   * an app-restart re-running setup doesn't fail — it simply does not
   * overwrite whatever the account's first device already established.
   * A second *device* of the same account generating its own, different
   * identity key is a real multi-device-linking gap this phase does not
   * solve (see the Phase 6 report's "remaining limitations") — it is
   * silently not adopted here rather than corrupting the account's one
   * true identity key.
   */
  registerIdentityKey: protectedProcedure
    .input(z.object({ publicKey: base64Bytes }))
    .mutation(async ({ ctx, input }) => {
      enforceRateLimit(`e2ee:registerIdentityKey:device:${ctx.device.id}`, 10, 60 * 60 * 1000);
      await assertCallerDeviceActive(ctx);

      await ctx.db
        .update(users)
        .set({ identitySigningPublicKey: Buffer.from(input.publicKey, 'base64') })
        .where(and(eq(users.id, ctx.user.id), isNull(users.identitySigningPublicKey)));

      return { registered: true as const };
    }),

  /**
   * Phase 6: writes this device's MLS credential public key and its
   * cross-signature (`devices.mlsCredentialPublicKey` /
   * `identityCrossSignature`) — same "declared since Phase 5A/5B, never
   * written until now" gap as `registerIdentityKey`, scoped per-device
   * instead of per-account. Set-once/idempotent for the same reason.
   */
  registerDeviceCredential: protectedProcedure
    .input(z.object({ credentialPublicKey: base64Bytes, crossSignature: base64Bytes }))
    .mutation(async ({ ctx, input }) => {
      enforceRateLimit(`e2ee:registerDeviceCredential:device:${ctx.device.id}`, 10, 60 * 60 * 1000);
      await assertCallerDeviceActive(ctx);

      await ctx.db
        .update(devices)
        .set({
          mlsCredentialPublicKey: Buffer.from(input.credentialPublicKey, 'base64'),
          identityCrossSignature: Buffer.from(input.crossSignature, 'base64'),
        })
        .where(and(eq(devices.id, ctx.device.id), isNull(devices.mlsCredentialPublicKey)));

      return { registered: true as const };
    }),

  /** Publishes this device's freshly-generated public KeyPackages (Phase 5B `generateKeyPackages` output). */
  publishKeyPackages: protectedProcedure
    .input(z.object({ keyPackages: z.array(base64Bytes).min(1).max(50) }))
    .mutation(async ({ ctx, input }) => {
      // Publishing is infrequent (only when a device's KeyPackage pool
      // runs low) and bounded to 50 per call already — a generous cap is
      // mainly to stop a compromised/scripted device from flooding its
      // own row set.
      enforceRateLimit(`e2ee:publishKeyPackages:device:${ctx.device.id}`, 20, 60 * 60 * 1000);
      await assertCallerDeviceActive(ctx);

      await ctx.db.insert(deviceKeyPackages).values(
        input.keyPackages.map((kp) => ({
          deviceId: ctx.device.id,
          publicKeyPackage: Buffer.from(kp, 'base64'),
        })),
      );
      return { published: input.keyPackages.length };
    }),

  /**
   * Consumes (returns and deletes) one unconsumed KeyPackage for the
   * given device — KeyPackages are single-use, per OpenMLS's own
   * documentation (see the Phase 5A/5B research). Returns null if none
   * are currently published.
   *
   * Phase 5D: also requires the *target* device to still be active.
   * Unlike `listActiveDeviceIds` (which already filtered on
   * `revokedAt`), this endpoint previously looked up KeyPackages purely
   * by `deviceId` with no join against the device's revocation state —
   * so a caller who already knew a revoked device's ID could still be
   * handed a Welcome-addressable KeyPackage for it, if that device's rows
   * hadn't been cleaned up. Revoked devices must not be addressable as
   * trusted, active group members.
   */
  consumeKeyPackage: protectedProcedure
    .input(z.object({ targetDeviceId: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      // Consuming is how a caller adds a peer device to a group — bound
      // it generously above normal usage (group creation touches this a
      // handful of times, not dozens) to blunt scripted KeyPackage-pool
      // exhaustion against a target device.
      enforceRateLimit(`e2ee:consumeKeyPackage:device:${ctx.device.id}`, 30, 5 * 60 * 1000);
      await assertCallerDeviceActive(ctx);

      // Audit fix: this was previously a SELECT then a separate DELETE.
      // Two concurrent consumeKeyPackage calls for the same
      // targetDeviceId (e.g. two people starting a conversation with the
      // same target at once, or a client retrying) could both SELECT the
      // same "unconsumed" row before either DELETEd it, handing out the
      // identical one-time KeyPackage twice — violating the single-use
      // invariant this endpoint's own doc comment above requires.
      // Locking the candidate row FOR UPDATE inside a transaction (with
      // SKIP LOCKED so a second concurrent caller finds no available row
      // instead of blocking on the first) makes select-then-delete
      // atomic with respect to other callers — the same class of fix
      // `createConversation` above already uses for its own concurrent
      // request race, just row-level instead of an advisory lock since
      // there's a concrete row to lock here.
      return ctx.db.transaction(async (tx) => {
        const [row] = await tx
          .select({ id: deviceKeyPackages.id, publicKeyPackage: deviceKeyPackages.publicKeyPackage })
          .from(deviceKeyPackages)
          .innerJoin(devices, eq(devices.id, deviceKeyPackages.deviceId))
          .where(and(eq(deviceKeyPackages.deviceId, input.targetDeviceId), isNull(devices.revokedAt)))
          .orderBy(asc(deviceKeyPackages.createdAt))
          .limit(1)
          .for('update', { of: deviceKeyPackages, skipLocked: true });

        if (!row) {
          return { keyPackage: null };
        }

        await tx.delete(deviceKeyPackages).where(eq(deviceKeyPackages.id, row.id));

        ctx.log.info({ targetDeviceId: input.targetDeviceId }, 'key package consumed');
        return { keyPackage: row.publicKeyPackage.toString('base64') };
      });
    }),

  /**
   * Creates a direct conversation between the caller and another user.
   * Its ID doubles as the MLS GroupId (client-side only — see
   * schema.ts). Idempotent as of Phase 6: if the two users already have
   * a direct conversation, returns its existing id instead of creating
   * a duplicate — a "start conversation" UI action is naturally
   * re-triggerable (tapping a search result twice, re-opening an
   * existing chat via search) and must not fork a second, empty
   * conversation + a second MLS group each time.
   */
  createConversation: protectedProcedure
    .input(z.object({ otherUserId: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      enforceRateLimit(`e2ee:createConversation:device:${ctx.device.id}`, 20, 60 * 60 * 1000);
      await assertCallerDeviceActive(ctx);

      if (input.otherUserId === ctx.user.id) {
        throw new TRPCError({ code: 'BAD_REQUEST', message: 'Cannot create a conversation with yourself.' });
      }

      // Two concurrent calls for the same pair (double tap, a client
      // retrying a request it thinks failed, two devices of the same
      // account, or the other member starting the conversation from
      // their side at the same moment) previously raced the "check for
      // an existing direct conversation, else insert one" logic below:
      // both could read "none exists" before either had committed its
      // insert, producing two separate `conversations` rows for the same
      // pair. There's no schema-level uniqueness constraint on a
      // direct-conversation member pair (only conversation_members'
      // (conversation_id, user_id) primary key, which doesn't help
      // here), so the fix is to serialize this whole check-then-insert
      // per pair instead.
      //
      // pg_advisory_xact_lock is transaction-scoped — it auto-releases on
      // commit/rollback/connection loss, needs no manual unlock, and
      // costs nothing when uncontended. Keying it off the *sorted* pair
      // means both members' calls (or two devices of either) contend for
      // the exact same lock regardless of who calls first.
      return ctx.db.transaction(async (tx) => {
        const [a, b] = [ctx.user.id, input.otherUserId].sort();
        await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${a} || ':' || ${b}))`);

        const otherMembers = alias(conversationMembers, 'other_members_cc');
        const [existing] = await tx
          .select({ conversationId: conversations.id })
          .from(conversationMembers)
          .innerJoin(conversations, eq(conversations.id, conversationMembers.conversationId))
          .innerJoin(
            otherMembers,
            and(eq(otherMembers.conversationId, conversationMembers.conversationId), eq(otherMembers.userId, input.otherUserId)),
          )
          .where(and(eq(conversationMembers.userId, ctx.user.id), eq(conversations.type, 'direct')))
          .limit(1);

        if (existing) {
          return { conversationId: existing.conversationId };
        }

        const [conversation] = await tx
          .insert(conversations)
          .values({ type: 'direct' })
          .returning({ id: conversations.id });

        if (!conversation) {
          throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'Failed to create conversation.' });
        }

        await tx.insert(conversationMembers).values([
          { conversationId: conversation.id, userId: ctx.user.id },
          { conversationId: conversation.id, userId: input.otherUserId },
        ]);

        return { conversationId: conversation.id };
      });
    }),

  /**
   * Phase 6: lists the caller's direct (1:1) conversations, each paired
   * with the *other* member's public profile — this is what powers the
   * chat list. Deliberately returns no message content or preview text
   * (the server cannot decrypt, and this phase's chat-list preview is
   * built client-side from the local decrypted-message cache instead);
   * only conversation identity and the other participant's public
   * profile, both of which the caller is already a legitimate member of.
   * Group conversations (`type: 'group'`) are excluded — out of scope
   * for this phase.
   */
  listConversations: protectedProcedure.query(async ({ ctx }) => {
    const otherMembers = alias(conversationMembers, 'other_members');

    const rows = await ctx.db
      .select({
        conversationId: conversations.id,
        createdAt: conversations.createdAt,
        otherUserId: users.id,
        otherUsername: users.username,
        otherDisplayName: users.displayName,
      })
      .from(conversationMembers)
      .innerJoin(conversations, eq(conversations.id, conversationMembers.conversationId))
      .innerJoin(
        otherMembers,
        and(eq(otherMembers.conversationId, conversationMembers.conversationId), ne(otherMembers.userId, ctx.user.id)),
      )
      .innerJoin(users, eq(users.id, otherMembers.userId))
      .where(and(eq(conversationMembers.userId, ctx.user.id), eq(conversations.type, 'direct')))
      .orderBy(desc(conversations.createdAt));

    return rows.map((row) => ({
      conversationId: row.conversationId,
      createdAt: row.createdAt.toISOString(),
      otherUser: { id: row.otherUserId, username: row.otherUsername, displayName: row.otherDisplayName },
    }));
  }),

  /**
   * Stores one opaque ciphertext blob — an application message or an
   * MLS Welcome — for later retrieval. The server never decodes,
   * inspects, or transforms `ciphertext` beyond base64->Buffer; it is
   * bytea end to end.
   */
  sendMessage: protectedProcedure
    .input(
      z.object({
        conversationId: z.string().uuid(),
        ciphertext: base64Bytes,
        messageType: z.enum(['application', 'welcome']),
        // Required for 'welcome' (single addressed device), must be
        // absent for 'application' (any conversation member may fetch it).
        recipientDeviceId: z.string().uuid().optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      // Generous per-device budget matched to a real chat's cadence
      // (bursts of several messages/sec are normal) while still bounding
      // a scripted flood.
      enforceRateLimit(`e2ee:sendMessage:device:${ctx.device.id}`, 60, 60 * 1000);
      await assertCallerDeviceActive(ctx);

      const [membership] = await ctx.db
        .select({ userId: conversationMembers.userId })
        .from(conversationMembers)
        .where(and(eq(conversationMembers.conversationId, input.conversationId), eq(conversationMembers.userId, ctx.user.id)))
        .limit(1);

      if (!membership) {
        throw new TRPCError({ code: 'FORBIDDEN', message: 'Not a member of this conversation.' });
      }

      if (input.messageType === 'welcome' && !input.recipientDeviceId) {
        throw new TRPCError({ code: 'BAD_REQUEST', message: 'recipientDeviceId is required for welcome messages.' });
      }

      const [message] = await ctx.db
        .insert(messages)
        .values({
          conversationId: input.conversationId,
          senderDeviceId: ctx.device.id,
          recipientDeviceId: input.recipientDeviceId ?? null,
          messageType: input.messageType,
          ciphertext: Buffer.from(input.ciphertext, 'base64'),
        })
        .returning({ id: messages.id });

      if (!message) {
        throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'Failed to store message.' });
      }

      if (input.messageType === 'application') {
        // Not awaited: a slow or unavailable push provider must never fail or delay the send itself.
        notifyNewMessage({ db: ctx.db, log: ctx.log, conversationId: input.conversationId, senderUserId: ctx.user.id }).catch((err) =>
          ctx.log.warn({ err }, 'push notification fan-out failed'),
        );
      }

      return { messageId: message.id };
    }),

  /**
   * Returns opaque ciphertext rows for a conversation — application
   * messages (any member) plus any 'welcome' messages addressed
   * specifically to the caller's current device. Never returns another
   * device's addressed Welcome.
   */
  fetchMessages: protectedProcedure.input(z.object({ conversationId: z.string().uuid() })).query(async ({ ctx, input }) => {
    // Read-only and legitimately polled at a decent cadence by clients
    // without a push/websocket channel yet — generous ceiling, mainly to
    // blunt scripted hammering rather than shape normal usage. Not
    // gated on device-revocation state (unlike the mutating endpoints
    // above): a revoked device reading ciphertext for conversations it
    // already had access to is materially lower-severity than one still
    // publishing new trust material, and this is the E2EE endpoint most
    // sensitive to added per-call latency.
    enforceRateLimit(`e2ee:fetchMessages:device:${ctx.device.id}`, 120, 60 * 1000);

    const [membership] = await ctx.db
      .select({ userId: conversationMembers.userId })
      .from(conversationMembers)
      .where(and(eq(conversationMembers.conversationId, input.conversationId), eq(conversationMembers.userId, ctx.user.id)))
      .limit(1);

    if (!membership) {
      throw new TRPCError({ code: 'FORBIDDEN', message: 'Not a member of this conversation.' });
    }

    const rows = await ctx.db
      .select({
        id: messages.id,
        senderDeviceId: messages.senderDeviceId,
        messageType: messages.messageType,
        ciphertext: messages.ciphertext,
        createdAt: messages.createdAt,
      })
      .from(messages)
      .where(
        and(
          eq(messages.conversationId, input.conversationId),
          or(isNull(messages.recipientDeviceId), eq(messages.recipientDeviceId, ctx.device.id)),
        ),
      )
      .orderBy(asc(messages.createdAt));

    return rows.map((row) => ({
      id: row.id,
      senderDeviceId: row.senderDeviceId,
      messageType: row.messageType,
      ciphertext: row.ciphertext.toString('base64'),
      createdAt: row.createdAt.toISOString(),
    }));
  }),

  /**
   * Lists a user's active AND E2EE-ready device IDs — needed to address a
   * KeyPackage/Welcome request. Returns IDs only, no other device metadata.
   *
   * Bug fix: this previously filtered only on `revokedAt IS NULL`, so a
   * device that exists (created at login/register) but never finished
   * `registerDeviceCredential` — because its `ensureE2eeSetup` is still
   * in flight, failed, or (on web, where the native MLS module is
   * unavailable) can never run — was still reported as an addressable
   * target. `consumeKeyPackage` would then correctly find no KeyPackage
   * for it, and if that happened to be the caller's only candidate
   * device, `startConversation` failed with "isn't ready to receive
   * encrypted messages yet" even when the recipient had a genuinely
   * ready device that just wasn't the one considered. Requiring
   * `mlsCredentialPublicKey IS NOT NULL` here restricts this list to
   * devices that have actually completed credential registration, which
   * is the real precondition for being a valid KeyPackage/Welcome target.
   */
  listActiveDeviceIds: protectedProcedure.input(z.object({ userId: z.string().uuid() })).query(async ({ ctx, input }) => {
    // Read-only, but this is a per-user device-enumeration primitive —
    // bounded generously enough for legitimate group-membership checks
    // (which may look up several users in a row) while blunting scripted
    // enumeration of many users' device lists.
    enforceRateLimit(`e2ee:listActiveDeviceIds:device:${ctx.device.id}`, 60, 5 * 60 * 1000);

    const rows = await ctx.db
      .select({ id: devices.id })
      .from(devices)
      .where(and(eq(devices.userId, input.userId), isNull(devices.revokedAt), isNotNull(devices.mlsCredentialPublicKey)));
    return rows.map((r) => r.id);
  }),
});
